# kubernetes/app/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-{{COLOR}}
# ...
spec:
# ...
  template:
# ...
    spec:
      containers:
      - name: demo-app
        # UPDATED: We will inject the entire ECR image URI from Jenkins
        image: {{IMAGE_URI}}
        ports:
        - containerPort: 8080 # Back to 8080 for the sample-app
        env:
        - name: APP_COLOR
          value: "{{COLOR}}"