apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: default
spec:
  type: LoadBalancer # Exposes the app to the internet
  ports:
  - port: 80
    targetPort: 8080
  selector:
    # Initially, we point to nothing, or to the first deployment (e.g., blue)
    app: demo-app
    color: blue