apiVersion: v1
kind: Service
metadata:
  name: demo-app-service-green-internal
  namespace: default
spec:
  type: ClusterIP # Only accessible within the cluster
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo-app
    color: green