# kubernetes/jenkins/values.yaml

controller:
  # Using the correct nested structure for the image
  image:
    repository: "jenkins/jenkins"
    tag: "lts-jdk17"

  serviceType: LoadBalancer
  
  # Unpinned plugin versions to let Jenkins resolve dependencies
  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - blueocean
  
  serviceAccount:
    create: true
    name: "jenkins"

# RBAC settings
rbac:
  create: true
  clusterRole: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: jenkins-cluster-admin
    rules:
      - apiGroups: ["*"]
        resources: ["*"]
        verbs: ["*"]
  clusterRoleBinding: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: jenkins-cluster-admin-binding
    subjects:
    - kind: ServiceAccount
      name: jenkins
      namespace: jenkins
    roleRef:
      kind: ClusterRole
      name: jenkins-cluster-admin
      apiGroup: rbac.authorization.k8s.io

# Persistence and securityContext settings
persistence:
  enabled: true
  storageClass: "gp3"
  size: "10Gi"
  securityContext:
    fsGroup: 1000
    runAsUser: 1000